name: Release Python Project

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # If your project has requirements.txt, uncomment the next line
        # pip install -r requirements.txt

    - name: Create .exe using pyinstaller
      run: |
        mkdir -p dist
        # Replace 'main.py' with the entry point of your project
        pyinstaller --onefile --distpath dist MetrologyTestInterface.py

    - name: Upload .exe Artifact
      uses: actions/upload-artifact@v4
      with:
        name: application.exe
        path: dist/main.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: application.exe

    - name: Install GitHub CLI
      run: sudo apt-get install gh -y

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: "v1.0.${{ github.run_number }}"
      run: |
        # Create the release
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --generate-notes \
            application.exe
