name: Build EXE using PyInstaller

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install matplotlib  # If needed

      - name: Build EXE with PyInstaller
        run: pyinstaller -F metrology_test_interface.spec

      - name: Verify EXE exists
        run: |
          if (Test-Path "dist/MetrologyTestInterface/MetrologyTestInterface.exe") {
            Write-Host "EXE file exists."
          } else {
            Write-Host "EXE file does not exist!"
          }

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: MetrologyTestInterface
          path: dist/MetrologyTestInterface/MetrologyTestInterface.exe

  release:
    needs: build
    runs-on: ubuntu-latest  # Use Ubuntu for the release job to utilize GitHub CLI

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: MetrologyTestInterface

    - name: Install GitHub CLI
      run: sudo apt-get install gh -y

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: "v1.0.0-${{ github.run_number }}"
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --generate-notes \
            MetrologyTestInterface.exe
