name: Release Python Project

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Create .exe using pyinstaller
      run: |
        mkdir -p dist
        pyinstaller --onefile --distpath dist MetrologyTestInterface.py

    - name: Check dist directory
      run: ls -la dist  # Check if the .exe file is generated

    - name: Upload .exe Artifact
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: dist/MetrologyTestInterface.exe  # Ensure this path matches the actual file name and location

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: application

    - name: Install GitHub CLI
      run: sudo apt-get install gh -y

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: "v1.0.${{ github.run_number }}"
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --generate-notes \
            MetrologyTestInterface.exe
